# Wedwise demonstration of an API spec in YAML
swagger: '2.0'
info:
  title: Wedwise
  description: Wedwise API 
  version: "1.0.0"
# the domain of the service
host: api.wedwise.com
# array of all schemes that your API supports
schemes:
  - https
# will be prefixed to all paths
basePath: /v1
produces:
  - application/json
paths:
  /register:
    post:
      parameters:
        - in: formData
          name: firstname
          description: First Name (Optional)
          type: string
        - in: formData
          name: lastname
          description: Last Name (Optional)
          type: string
        - in: formData
          name: email
          description: user email address 
          required: true
          type: string
        - in: formData
          name: password
          description: password of user
          required: true
          type: string		  
      responses:
        200:
          description: successful operation
          schema:
            $ref: "#/definitions/RegisterResponse"
        400:
          description: Invalid Request
  /registerConfirm:
    post:
      parameters:
        - name: cid
          in: query
          type: string
          required: true
          description: Confirmation uid
      responses:
        200:
          description: User is confirmed by wedwise platform
definitions:
  RegisterResponse:
    properties:
      uid:
        type: string
        format: uuid
        description: user unique wedwise id
      message:
        type: string
        description: message indicates further action need to perform
      userStatus:
        type: string
        description: User Status
