#!/usr/bin/env python
# coding: utf-8

"""
DefaultApi.py
Copyright 2015 Reverb Technologies, Inc.

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.

NOTE: This class is auto generated by the swagger code generator program. Do not edit the class manually.
"""
import sys
import os
import urllib

from models import *


class DefaultApi(object):

    def __init__(self, apiClient):
      self.apiClient = apiClient

    
    
    def register_post(self, **kwargs):
        """
        

        Args:
            firstname, str: First Name (Optional) (required)
            lastname, str: Last Name (Optional) (required)
            email, str: user email address (required)
            password, str: password of user (required)
            

        Returns: RegisterResponse
        """

        allParams = ['firstname', 'lastname', 'email', 'password']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method register_post" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/register'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        accepts = []
        headerParams['Accept'] = ', '.join(accepts)

        content_types = []
        headerParams['Content-Type'] = content_types[0] if len(content_types) > 0 else 'application/json'

        

        

        

        
        if ('firstname' in params):
            formParams['firstname'] = params['firstname']
        
        if ('lastname' in params):
            formParams['lastname'] = params['lastname']
        
        if ('email' in params):
            formParams['email'] = params['email']
        
        if ('password' in params):
            formParams['password'] = params['password']
        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        if not response:
            return None

        responseObject = self.apiClient.deserialize(response, 'RegisterResponse')
        return responseObject
        
        
        
    
    def register_confirm_post(self, **kwargs):
        """
        

        Args:
            cid, str: Confirmation uid (required)
            

        Returns: 
        """

        allParams = ['cid']

        params = locals()
        for (key, val) in params['kwargs'].iteritems():
            if key not in allParams:
                raise TypeError("Got an unexpected keyword argument '%s' to method register_confirm_post" % key)
            params[key] = val
        del params['kwargs']

        resourcePath = '/registerConfirm'
        resourcePath = resourcePath.replace('{format}', 'json')
        method = 'POST'

        queryParams = {}
        headerParams = {}
        formParams = {}
        files = {}
        bodyParam = None

        accepts = []
        headerParams['Accept'] = ', '.join(accepts)

        content_types = []
        headerParams['Content-Type'] = content_types[0] if len(content_types) > 0 else 'application/json'

        
        if ('cid' in params):
            queryParams['cid'] = self.apiClient.toPathValue(params['cid'])
        

        

        

        

        

        postData = (formParams if formParams else bodyParam)

        response = self.apiClient.callAPI(resourcePath, method, queryParams,
                                          postData, headerParams, files=files)

        
        
        
    


